import { auth, db, collection, getDocs, getDoc, addDoc, updateDoc, deleteDoc, doc, query, orderBy, serverTimestamp } from "./firebase-config.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";

const ADMIN_EMAIL = "chanikya.bommidi143@gmail.com";
const $ = (id) => document.getElementById(id);
const money = new Intl.NumberFormat("en-IN");
let orders = [], products = [], editingId = null;

const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const stockInfo = (product) => { const stock = Number(product.stock ?? 0); return stock <= 0 ? ["Out of stock", "out"] : stock <= 5 ? ["Low stock", "low"] : ["In stock", "in"]; };
const available = (product) => Number(product.stock ?? 0) > 0 && (product.status || "Active") === "Active";

function setView(view) { document.querySelectorAll(".view").forEach((node) => node.classList.toggle("active", node.id === `${view}View`)); document.querySelectorAll(".nav-item").forEach((node) => node.classList.toggle("active", node.dataset.view === view)); $("pageTitle").textContent = view === "dashboard" ? "Overview" : view[0].toUpperCase() + view.slice(1); if (view === "products") renderProducts(); if (view === "inventory") renderInventory(); }
function updateStats() { const revenue = orders.reduce((sum, order) => sum + Number(order.total || 0), 0); $("totalOrders").textContent = orders.length; $("totalRevenue").textContent = `₹${money.format(revenue)}`; $("pendingOrders").textContent = orders.filter((order) => ["New", "Confirmed", "Packed"].includes(order.status || "New")).length; $("deliveredOrders").textContent = orders.filter((order) => order.status === "Delivered").length; }
function renderOrders() { const search = $("searchOrders").value.trim().toLowerCase(); const status = $("statusFilter").value; const filtered = orders.filter((order) => [order.id, order.customerName, order.phone].join(" ").toLowerCase().includes(search) && (status === "All" || (order.status || "New") === status)); $("ordersList").innerHTML = filtered.length ? filtered.map((order) => `<article class="order-card"><div class="order-head"><div><p class="eyebrow">ORDER ${order.id.slice(-6).toUpperCase()}</p><h3>${escapeHtml(order.customerName || "Customer")}</h3><p>${escapeHtml(order.phone || "No phone provided")}</p></div><strong>₹${money.format(Number(order.total || 0))}</strong></div><div class="order-items">${(order.items || []).map((item) => `<span>${escapeHtml(item.name)} <b>×${item.qty}</b></span>`).join("") || "No items recorded"}</div><div class="order-actions"><select data-order-status="${order.id}">${["New", "Confirmed", "Packed", "Shipped", "Delivered", "Cancelled"].map((item) => `<option ${item === (order.status || "New") ? "selected" : ""}>${item}</option>`).join("")}</select><button class="text-button" data-invoice="${order.id}">Invoice</button><button class="text-button danger" data-delete-order="${order.id}">Delete</button></div></article>`).join("") : '<div class="empty-state">No orders match these filters.</div>'; }
function renderProducts() { const search = $("productSearch").value.trim().toLowerCase(); const sort = $("productSort").value; const list = products.filter((product) => [product.name, product.category, product.sku].join(" ").toLowerCase().includes(search)).sort((a,b) => sort === "priceLow" ? Number(a.price)-Number(b.price) : sort === "priceHigh" ? Number(b.price)-Number(a.price) : sort === "stock" ? Number(a.stock ?? 0)-Number(b.stock ?? 0) : String(a.name || "").localeCompare(String(b.name || ""))); $("productsList").innerHTML = list.length ? list.map((product) => { const [label, style] = stockInfo(product); return `<article class="product-row"><img src="${escapeHtml(product.image || "")}" alt=""><div class="product-row-main"><p class="eyebrow">${escapeHtml(product.category || "Uncategorised")}</p><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.sku || "No SKU")} · ₹${money.format(Number(product.price || 0))}</p></div><span class="status ${style}">${label}</span><div class="row-actions"><button class="text-button" data-edit-product="${product.id}">Edit</button><button class="text-button danger" data-delete-product="${product.id}">Delete</button></div></article>`; }).join("") : '<div class="empty-state">No products found.</div>'; }
function renderInventory() { const totalUnits = products.reduce((sum, product) => sum + Number(product.stock ?? 0), 0), low = products.filter((product) => Number(product.stock ?? 0) > 0 && Number(product.stock ?? 0) <= 5).length, out = products.filter((product) => !available(product)).length; $("inventorySummary").innerHTML = `<article><span>Total units</span><strong>${totalUnits}</strong></article><article><span>Low stock</span><strong>${low}</strong></article><article><span>Unavailable</span><strong>${out}</strong></article>`; $("inventoryList").innerHTML = products.length ? products.slice().sort((a,b) => Number(a.stock ?? 0)-Number(b.stock ?? 0)).map((product) => { const [label, style] = stockInfo(product); return `<article class="inventory-row"><img src="${escapeHtml(product.image || "")}" alt=""><div><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.sku || "No SKU")} · ${escapeHtml(product.category || "Uncategorised")}</p></div><span class="status ${style}">${label}</span><div class="stock-control"><button data-stock="decrease" data-id="${product.id}" aria-label="Decrease stock">−</button><strong>${Number(product.stock ?? 0)}</strong><button data-stock="increase" data-id="${product.id}" aria-label="Increase stock">+</button></div></article>`; }).join("") : '<div class="empty-state">No product inventory yet.</div>'; }
async function loadData() { try { const [orderSnap, productSnap] = await Promise.all([getDocs(query(collection(db,"orders"), orderBy("createdAt","desc"))), getDocs(collection(db,"products"))]); orders = orderSnap.docs.map((entry) => ({id:entry.id,...entry.data()})); products = productSnap.docs.map((entry) => ({id:entry.id,...entry.data()})); updateStats(); renderOrders(); } catch (error) { console.error(error); $("ordersList").innerHTML = '<div class="empty-state">Unable to load data. Please refresh.</div>'; } }
function resetForm() { editingId = null; $("productForm").reset(); $("productStock").value = 0; $("productStatus").value = "Active"; $("imagePreview").removeAttribute("src"); $("modalTitle").textContent = "New product"; $("saveProduct").textContent = "Save product"; }
function showModal(product) { resetForm(); if (product) { editingId = product.id; $("modalTitle").textContent = "Edit product"; $("saveProduct").textContent = "Update product"; ["Image","Name","Category","Subcategory","SKU","Stock","Status","Weight","Material","Color","Description","Price"].forEach((key) => { const node = $(`product${key}`); if(node) node.value = product[key.toLowerCase()] ?? ""; }); $("productTags").value = (product.tags || []).join(", "); $("imagePreview").src = product.image || ""; } $("productModal").showModal(); }
async function saveProduct(event) { event.preventDefault(); const image = $("productImage").value.trim(), name = $("productName").value.trim(), price = Number($("productPrice").value); if (!image || !name || !Number.isFinite(price) || price < 0) return alert("Please enter a product image, name and valid price."); const data = { image, name, price, category:$("productCategory").value.trim(), subcategory:$("productSubcategory").value.trim(), sku:$("productSKU").value.trim(), stock:Math.max(0,Number($("productStock").value || 0)), status:$("productStatus").value, weight:$("productWeight").value.trim(), material:$("productMaterial").value.trim(), color:$("productColor").value.trim(), tags:$("productTags").value.split(",").map((tag)=>tag.trim()).filter(Boolean), description:$("productDescription").value.trim(), updatedAt:serverTimestamp() }; try { if (editingId) await updateDoc(doc(db,"products",editingId),data); else await addDoc(collection(db,"products"),{...data,createdAt:serverTimestamp()}); $("productModal").close(); await loadData(); renderProducts(); } catch(error) { console.error(error); alert("Unable to save product."); } }

document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", () => setView(button.dataset.view))); $("addProductBtn").addEventListener("click", () => showModal()); $("productImage").addEventListener("input", () => { $("imagePreview").src = $("productImage").value.trim(); }); $("productForm").addEventListener("submit", saveProduct); ["searchOrders","statusFilter"].forEach((id) => $(id).addEventListener(id === "statusFilter" ? "change" : "input", renderOrders)); ["productSearch","productSort"].forEach((id) => $(id).addEventListener(id === "productSort" ? "change" : "input", renderProducts));
document.querySelectorAll("[data-close-modal]").forEach((button) => button.addEventListener("click", () => $("productModal").close()));
$("ordersList").addEventListener("change", async (event) => { const id = event.target.dataset.orderStatus; if (!id) return; await updateDoc(doc(db,"orders",id),{status:event.target.value}); const order=orders.find((item)=>item.id===id); if(order) order.status=event.target.value; updateStats(); renderOrders(); });
$("ordersList").addEventListener("click", async (event) => { const id = event.target.dataset.deleteOrder; if (id) { if (!confirm("Delete this order?")) return; await deleteDoc(doc(db,"orders",id)); await loadData(); return; } if (event.target.dataset.invoice) window.open(`invoice.html?id=${event.target.dataset.invoice}`,"_blank"); });
$("productsList").addEventListener("click", async (event) => { const id=event.target.dataset.editProduct || event.target.dataset.deleteProduct; if(!id) return; if(event.target.dataset.deleteProduct) { if(!confirm("Delete this product?")) return; await deleteDoc(doc(db,"products",id)); await loadData(); renderProducts(); } else { const snap=await getDoc(doc(db,"products",id)); if(snap.exists()) showModal({id:snap.id,...snap.data()}); } });
$("inventoryList").addEventListener("click", async (event) => { const id=event.target.dataset.id; if(!id) return; const product=products.find((item)=>item.id===id); const delta=event.target.dataset.stock === "increase" ? 1 : -1; if(!product || delta < 0 && Number(product.stock ?? 0) <= 0) return; await updateDoc(doc(db,"products",id),{stock:Math.max(0,Number(product.stock ?? 0)+delta),updatedAt:serverTimestamp()}); await loadData(); renderInventory(); });
$("logoutBtn").addEventListener("click", () => signOut(auth));
onAuthStateChanged(auth, (user) => { if (!user || user.email?.toLowerCase() !== ADMIN_EMAIL) { if(user) signOut(auth); window.location.href="login.html"; return; } loadData(); });
